#!/usr/bin/env bash

# generating authors for the project after a commit message has been done

{
	cat <<-'EOH'
	# This file lists all individuals having contributed content to the repository
	# For how it is generated, see 'generateAuthors'
	EOH
	echo
	git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf
} > AUTHORS
